include:
  - board: seeeduino_xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: roBa_L
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2        # ← mdbt50q_db_40 から nice_nano_v2 に変更
    shield: roBa_dongle
