include:
  # ---------------------------------------
  # メインファームウェア
  # ---------------------------------------
  # 左手 (XIAO BLE)
  - board: xiao_ble
    shield: roBa_L
    snippet: studio-rpc-usb-uart

  # 右手 (XIAO BLE)
  - board: xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart

  # ドングル (Nice!Nano v2)
  - board: nice_nano
    shield: roBa_dongle dongle_display

  # ---------------------------------------
  # リセット用ファームウェア
  # ---------------------------------------
  - board: xiao_ble
    shield: settings_reset
  - board: nice_nano
    shield: settings_reset
