include:
  # ---------------------------------------
  # メインファームウェア
  # ---------------------------------------
  # 左手 (XIAO BLE)
  - board: seeeduino_xiao_ble
    shield: roBa_L
    snippet: studio-rpc-usb-uart

  # 右手 (XIAO BLE)
  - board: seeeduino_xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart

  # ドングル (Nice!Nano v2)
  # ▼▼▼ 修正：board名を nice_nano に戻しました ▼▼▼
  - board: nice_nano
    shield: roBa_dongle dongle_display

  # ---------------------------------------
  # リセット用ファームウェア（便利ツール）
  # ---------------------------------------
  # 左右キーボード用 (XIAO BLE) のリセット
  - board: seeeduino_xiao_ble
    shield: settings_reset

  # ドングル用 (Nice!Nano v2) のリセット
  # ▼▼▼ 修正：board名を nice_nano に戻しました ▼▼▼
  - board: nice_nano
    shield: settings_reset
