include:
  # ---------------------------------------
  # メインファームウェア
  # ---------------------------------------
  # 左手 (XIAO BLE)
  - board: seeeduino_xiao_ble
    shield: roBa_L
    snippet: studio-rpc-usb-uart

  # 右手 (XIAO BLE)
  - board: seeeduino_xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart

  # ドングル (Nice!Nano v2)
  # ▼▼▼ 修正：dongle_display を追加して統合 ▼▼▼
  - board: nice_nano_v2
    shield: roBa_dongle dongle_display

  # ---------------------------------------
  # リセット用ファームウェア（便利ツール）
  # ---------------------------------------
  # 左右キーボード用 (XIAO BLE) のリセット
  - board: seeeduino_xiao_ble
    shield: settings_reset

  # ドングル用 (Nice!Nano v2) のリセット
  - board: nice_nano_v2
    shield: settings_reset
