include:
  # ---------------------------------------
  # メインファームウェア
  # ---------------------------------------
  # 左手 (XIAO BLE)
  - board: xiao_ble
    shield: roBa_L
    snippet: studio-rpc-usb-uart
    # ▼▼▼ 強制読み込み設定 (左) ▼▼▼
    cmake-args: -DZMK_EXTRA_MODULES="modules/drivers/zmk-pmw3610-driver;modules/drivers/zmk-dongle-display"

  # 右手 (XIAO BLE)
  - board: xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart
    # ▼▼▼ 強制読み込み設定 (右) ▼▼▼
    cmake-args: -DZMK_EXTRA_MODULES="modules/drivers/zmk-pmw3610-driver;modules/drivers/zmk-dongle-display"

  # ドングル (Nice!Nano v2)
  - board: nice_nano
    shield: roBa_dongle dongle_display
    # ▼▼▼ 強制読み込み設定 (ドングル) ▼▼▼
    cmake-args: -DZMK_EXTRA_MODULES="modules/drivers/zmk-pmw3610-driver;modules/drivers/zmk-dongle-display"

  # ---------------------------------------
  # リセット用ファームウェア
  # ---------------------------------------
  - board: xiao_ble
    shield: settings_reset
  - board: nice_nano
    shield: settings_reset
