include:
  # ▼▼▼ 左手 (XIAO BLE) ▼▼▼
  - board: xiao_ble
    shield: roBa_L
    snippet: studio-rpc-usb-uart

  # ▼▼▼ 右手 (XIAO BLE) ▼▼▼
  - board: xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart

  # ▼▼▼ 修正：リセット用ファイルも正式名称で作成 ▼▼▼
  - board: xiao_ble
    shield: settings_reset

# ▼▼▼ ドングル (XIAO BLE) ▼▼▼
  - board: xiao_ble
    shield: roBa_dongle
