include:
  # ▼▼▼ 修正：ボード名を正式名称に変更（roBa_R） ▼▼▼
  - board: seeeduino_xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart

  # ▼▼▼ 修正：ボード名を正式名称に変更（roBa_L） ▼▼▼
  - board: seeeduino_xiao_ble
    shield: roBa_L

  # ▼▼▼ 修正：リセット用ファイルも正式名称で作成 ▼▼▼
  - board: seeeduino_xiao_ble
    shield: settings_reset

    # ▼▼▼ ドングル (XIAO BLE) ※ここを修正！ ▼▼▼
  - board: seeeduino_xiao_ble
    shield: roBa_dongle
